first task version 2
muramidaza/junior-course-boilerplate pull request #1
Opened 2020-10-10 18:37 UTC by muramidaza

2020-10-10 18:58 UTC, CSSSR-School requested changes

2020-10-10 18:58 UTC, CSSSR-School commented on src/index.js
> +let products = data.slice(0, 3);
Давай будем придерживаться const-first-подхода и использовать `let` только тогда, когда хотим явно показать своим будущим коллегам, что эта переменная (или ссылка на неё) будет изменена.

2020-10-10 18:58 UTC, CSSSR-School commented on src/index.css
>    height: 1.4em;
Верстка, конечно, выходит за пределы нашего курса, но фиксированная высота в данной ситуации - спорный момент, который сильно привязан к количеству контента, переданного в список. Давай не будем усложнять то, на что сейчас нет реальной причины для усложнения, и сфокусируемся на реакте - нам здесь пока не нужны флексы)

2020-10-11 09:07 UTC, closed without merging

2020-10-11 09:08 UTC, muramidaza commented
Переделал