Develop
muramidaza/junior-course-boilerplate pull request #10
Opened 2020-11-12 10:50 UTC by muramidaza

Task 7
Add URL control
Add paginator
Add ducks

2020-11-14 00:48 UTC, CSSSR-School commented on src/components/ProductsList/index.js
> +		const MAX_RATING = this.props.maxRating;
В данном случае логичнее будет использовать такую конструкцию, так как написание MAX_RATING может ввести в заблуждение:
```javascript
		const { productsChunk, maxRating } = this.props;
```

2020-11-14 00:48 UTC, CSSSR-School commented on src/components/ProductsList/index.js
> +export {ProductsList};
Не выбивается ли этот экспорт из общего стиля?

2020-11-14 00:48 UTC, CSSSR-School commented on src/containers/FormFilter/types.js
> +const CHANGE_MINPRICE = 'FormFilter/reducer/CHANGE_MINPRICE';
Нужно ли указывать в описании каждого экшена `reducer`? Кажется, что это повторяется везде

2020-11-14 00:48 UTC, CSSSR-School commented on src/containers/ListContainer/index.js
> +	} else {
Не получится ли ограничиться более простой конструкцией, вроде такой?
```javascript
...
if (!equals(memoizedData, data)) {
        memoizedData = data;
	return data;
}

return memoizedData;
...
```

2020-11-14 00:48 UTC, CSSSR-School commented on src/containers/Paginator/ButtonLimit.js
> +			<button onClick={this.props.handleClick} className={'paginator__buttonlimit'}>
Очень рекомендую к кнопкам добавлять атрибут `type='button'`, иначе такая кнопка, случайно попавшая под тег `form` по-дефолту будет работать как `input[type='submit']`

2020-11-14 00:48 UTC, CSSSR-School commented on src/containers/Paginator/index.js
> +				{this.state.section > 0 && (<ButtonLimit innerText={'prev'} handleClick={this.handleClickPrev} />)}
`&&` сам по себе подразумевает `return`, так что круглые скобки тут не нужны ;)

2020-11-14 00:48 UTC, CSSSR-School commented on src/containers/Paginator/index.js
> +				{this.state.section < this.paginatorLimit && (<ButtonLimit innerText={'next'} handleClick={this.handleClickNext} />)}
Тут также не нужны скобки. Вообще, рекомендую такие условные рендеры вынести в отдельные функции с названиями вроде `renderSomething()`. Когда условий становится много, их очень тяжело читать.

2020-11-16 08:15 UTC, vislogurov requested changes

2020-11-16 08:15 UTC, vislogurov commented on src/components/ButtonLimit/ButtonLimit.js
> +export default class ButtonLimit extends logComponent {
Можно уже отказаться от наследования logComponent и наследоваться от Component. Это касается всех блоков.

2020-11-16 08:15 UTC, vislogurov commented on src/components/ResetButton/index.js
> +			<button type='button' onClick={this.props.onReset} className={'resetButton'}>Сбросить фильтры</button>
`type = reset`

2020-11-16 08:15 UTC, vislogurov commented on src/containers/App/index.js
> +		handleLoadInitData: (productsData, categoriesList, goodsInPage) => {
Кажется, тут лучше заюзать https://redux.js.org/api/bindactioncreators , визуально облегчит компонент

2020-11-16 08:15 UTC, vislogurov commented on src/containers/App/reducers.js
> +			return {...state, productsData: action.payload.productsData, categoriesList: action.payload.categoriesList, goodsInPage: action.payload.goodsInPage}
Предлагаю на этом этапе просто сложить все поля в payload, а уже на этапе чтения из стора провести деструктуризацию `{productsData, categoriesList, goodsInPage}`. Редюсер станет легче для чтения

2020-11-16 08:15 UTC, vislogurov commented on src/containers/App/selectors.js
> +import {createSelector} from 'reselect';
Вынеси все селекторы в **_общую_** директорию, в 99% они тебе понадобятся где-то ещё, кроме этого компонента.

2020-11-16 08:15 UTC, vislogurov commented on src/containers/FormFilter/index.js
>  		handleChangeMinPrice: (value) => {
Аналогично, посмотри в сторону bindActionCreators

2020-11-16 08:15 UTC, vislogurov commented on src/containers/ListContainer/index.js
> +function memoizeData(data) {
Такие utility-функции нужно выносить в общую директорию. если нужно будет заюзать мемоизацию где-то ещё, то придётся импортить и код этого компонента тоже (тут есть неочевидный подводный камень с дубликацией зависимостей)

2020-11-16 08:15 UTC, vislogurov commented on src/containers/ListContainer/index.js
> +		const prepareProductsDataMemo = memoizeData(prepareProductsData);
А вообще зачем тут отдельно мемоизированные данные? Разве их нельзя через мемоизированный селектор получить?

2020-11-16 08:15 UTC, vislogurov commented on src/containers/ListContainer/index.js
> +		const prepareProductsDataMemo = memoizeData(prepareProductsData);
Вопрос на засыпку)

2020-11-16 12:02 UTC, muramidaza commented on src/components/ButtonLimit/ButtonLimit.js
> +export default class ButtonLimit extends logComponent {
Жаль, можно было наблюдать какие компоненты рендерятся...

2020-11-16 17:08 UTC, vislogurov commented on src/components/ButtonLimit/ButtonLimit.js
> +export default class ButtonLimit extends logComponent {
В целом у тебя же есть нативная релизация sCU, можешь использовать её. 
при этом учти, что решение с логгером не prod-ready, деплоить такое нельзя.

2020-11-16 17:10 UTC, vislogurov approved these changes

2020-11-16 17:10 UTC, vislogurov commented on src/containers/ListContainer/index.js
> +import equals from 'ramda/src/equals';
А где в компонентe юзается equals?

2020-11-16 17:38 UTC, merged