Develop
muramidaza/junior-course-boilerplate pull request #6
Opened 2020-10-16 14:34 UTC by muramidaza

Задание 3: "Добавление модуля фильтрации по цене с проверкой и модуля логгирования"

2020-10-16 15:58 UTC, CSSSR-School requested changes

2020-10-16 15:58 UTC, CSSSR-School commented on package.json
> +    "csssr-school-utils": "https://github.com/CSSSR-School/junior-course-utils.git",
Поправь пожалуйста название пулл-реквеста. При таком рабочем флоу все пулл-реквесты придется называть Develop, что затруднит поиски нужного пр-а в будущем.

2020-10-16 15:58 UTC, CSSSR-School commented on package.json
> +    "logger": "0.0.1",
`"logger": "0.0.1",` не используется для решения текущей задачи - давай его удалим.

2020-10-16 15:58 UTC, CSSSR-School commented on src/components/FormFilter/index.css
> +.formFilter INPUT {
Верстка выходит за рамки нашего курса, но не рекомендую без веской причины привязывать стили к названиям тегов - любая правка разметки в таком случае требует и правок файла стилей, классы в этом плане гибче.

2020-10-16 15:58 UTC, CSSSR-School commented on src/components/FormFilter/index.js
> +					<input type="submit" value="Отправить" />
Верстка выходит за рамки нашего курса, но не рекомендую без веской причины использовать input[type="submit"] вместо button[type="submit"]. Кнопка для отправки формы является более явным тегом, проще стилизуется и более гибкая для размещения контента внутри себя.

2020-10-16 15:58 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +import {FormFilter} from '../FormFilter/index.js';
Кстати,  в случае с index.js импортировать можно напрямую обращаясь к папке: `import {FormFilter} from '../FormFilter'`

2020-10-16 15:58 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +		).slice(0, GOODS_IN_PAGE);
Такую логику будет проще читать и поддерживать, если разбивать её на логические куски, по-возможности используя неявный возврат в простых функциях. В нашем задании нет конкретной формулировки того, как должна происходить "обрезка", но предположим что речь будет идти об обрезке отфильтрованных товаров (как и предполагается сейчас):

```
// за пределами объявления компонента:
const filterProductByPrice = (products, minPrice, maxPrice) => {
  const predicateFn = ({price}) => price >= minPrice && price <= maxPrice;

  return products.filter(predicateFn)
}
const getProductsToShow = (products) => products.slice(0, GOODS_IN_PAGE);

// внутри компонента
render() {
  const filteredProducts = filterProductByPrice(this.props.productsData, this.state.filterData.minPrice, this.state.filterData.maxPrice)
  const productsToShow = getProductsToShow(filteredProducts)
}
```

2020-10-16 15:58 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +		this.state = {
Очень не рекомендую использовать вложенные структуры в стейте - есть шанс пропустить спрединг нужной сущности перед тем, как записывать новое значение.

2020-10-18 18:32 UTC, CSSSR-School requested changes

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/FormFilter/index.js
> +		this.handleSubmit = this.handleSubmit.bind(this);
привязка this не требуется для стрелочных функций - стрелочная функция не имеет собственного this, в то время как this обычной функции будет привязан к контексту вызова. Попробуй сам поэкспериментировать с определением этого метода как обычной (c bind и без него) и стрелочной функции, делая console.log(this) внутри вызова.)

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +const getProductsToShow = (products) => products.slice(0, GOODS_IN_PAGE);
Отлично! Мы вынесли функции за пределы компонента, получив возможность в будущем написать для них тесты, и упростив наш компонент.

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +			maxPrice: this.props.productsData.reduce((maxValue, elem) => {return elem.price > maxValue ? elem.price : maxValue;}, 0)
Давай вместо большой конструкции в стейте пока ограничимся тем, что просто укажем произвольные числа, входящие в ожидаемый диапазон стоимостей товаров. Если хочется все-таки "дожать" логику с выставлением цены в зависимости от цен товаров, то попробуй использовать https://github.com/CSSSR-School/junior-course-utils#maxBy и minBy, применяя их результаты в componentDidMount - этапе жизненного цикла, который просходит после того, как компонент был домавлен в DOM-дерево. Тогда мы получим компонент, который гарантированно быстро отрисуется (ладно, для этого случая будет не заметно, но сам подход того стоит), а затем уже обновит данные в своих фильтрах.

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +				<FormFilter changeFilter={this.changeFilter} maxPrice={this.state.maxPrice} minPrice={this.state.minPrice}/>
обычно подобные пропсы называют по шаблону: `onSomethingHappens`, то есть "когда что-то случается". То есть посыл не в том, что мы обязательно передаем сюда функцию, которая обработает изменение фильтра, а функцию, которая сделает то, что должно быть сделано при изменении фильтра - вообще не обязательно связанное с фильтром (закроет попап, изменит фон страницы и тд).

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/FormFilter/index.js
> +		this.props.changeFilter({minPrice: this.inputMinPrice.current.value, maxPrice: this.inputMaxPrice.current.value});
обычно подобные пропсы называют по шаблону: `onSomethingHappens`, то есть "когда что-то случается". В данном случае - `onChangeFilter`. То есть посыл не в том, что мы обязательно передаем сюда функцию, которая обработает изменение фильтра, а функцию, которая сделает то, что должно быть сделано при изменении фильтра - вообще не обязательно связанное с фильтром (закроет попап, изменит фон страницы и тд).

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +	changeFilter = (data) => {
такие функции принятно называть по шаблону `handleSomething`. В данном случае - `handleFilterChange`. То есть с той задумкой, что произойти по изменению фильтра может что угодно, и задача этой функции - обработать изменение фильтра, произведя все эти действия.

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsList/index.js
> +		const productsToShow = this.props.productsToShow;
А если нужно будет добавить еще одну переменную из пропсов, то придется добавлять еще одну строку. Давай попробуем использовать деструктуризацию: `const { productsToShow } = this.props;`

2020-10-18 18:32 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +			maxPrice: data.maxPrice >= 0 ? data.maxPrice : 0
Давай попробуем вместо этого установить min аттрибут для каждого из инпутов в фильтре. Просто для того, чтобы держать в учебном проекте такие вещи максимально простыми. Пока. Усложнять будем на занятии по подключению redux. ;)

2020-10-19 05:05 UTC, muramidaza commented on src/components/FormFilter/index.js
> +		this.handleSubmit = this.handleSubmit.bind(this);
Забыл переделать, в начале она у меня была обычная

2020-10-19 19:00 UTC, CSSSR-School requested changes

2020-10-19 19:00 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +import maxBy from 'csssr-school-utils/lib/maxBy';
Обрати внимание на https://github.com/CSSSR-School/junior-course-utils/blob/master/src/index.js - оттуда экспортируются все нужные нам функции. Можно забрать их вот так:
```
import {logger, maxBy, minBy} from 'csssr-school-utils/lib/
```

2020-10-19 19:00 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +				<FormFilter onChangeFilter={this.onChangeFilter} maxPrice={this.state.maxPrice} minPrice={this.state.minPrice}/>
В onChangeFilter передаем this.handleChangeFilter. То есть когда происходит какое-то событие (on), мы его обрабатываем (handle).

2020-10-19 19:00 UTC, CSSSR-School commented on src/components/FormFilter/index.js
> +				<form onSubmit={this.handleFilterChange}>
Немного неоднозначное место. Все-таки давай назовем хендлер как handleFilterSubmit - потому как запускается он именно на отправку этой формы, в то время как изменение его полей (то есть данных в любом из инпутов) никакого действия не производит. Возможно, что текущий нейминг был бы подходящим, если бы фильтр "оповещал" связанные компоненты о своем изменении сразу. Но мне нравится текущее поведение, так что давай просто поправим имена.

2020-10-20 15:54 UTC, CSSSR-School requested changes

2020-10-20 15:54 UTC, CSSSR-School commented on src/components/FormFilter/index.js
> +	}
Остался последний момент, указанный в задании - нужно чтобы каждый наш компонент в качестве базового использовал компонент LogRender. Давай создадим этот компонент c этой реализацией shouldComponentUpdate, после чего каждый из используемых React.Component-компонентов будет наследоваться (extends ) не от React.Component, а от LogRender. А уже LogRender - от React.Component.

2020-10-20 15:54 UTC, CSSSR-School commented on src/components/ProductsPage/index.js
> +				<FormFilter handleChangeFilter={this.handleChangeFilter} maxPrice={this.state.maxPrice} minPrice={this.state.minPrice} />
Логика должна быть такой: пропсы - это `on..`, внутренние методы-обработчики - это `handle`. То есть
```
<FormFilter onChangeFilter={this.handleChangeFilter} ... />
```
Проверь пожалуйста весь пулл-реквест на соответствие этому требованию.

2020-10-22 08:28 UTC, CSSSR-School requested changes

2020-10-22 08:28 UTC, CSSSR-School commented on package.json
> +    "react-addons-shallow-compare": "^15.6.2",
Смотрю, что в package.json зависимость есть, но в компоненте logComponent пакет не используется, по крайней мере в этой ветке :)
В целом, предлагаю либо добавить `shallowCompare` в shouldComponentUpdate, либо пока избавиться от зависимости для этого пулл реквеста.

2020-10-22 08:37 UTC, CSSSR-School approved these changes

2020-10-22 08:50 UTC, CSSSR-School approved these changes

2020-10-22 08:54 UTC, merged